branches:
  only:
    - 'master'

language: ruby
rvm:
  - 2.2.1

# before_install:
#   - gem install nokogiri -- --with-cflags='--std=gnu99'

script:
  - bundle exec rake db:migrate
  - bundle exec rake test